#pragma once

#define ENCODER_RESOLUTION 4

#define WS2812_DI_PIN GP0
#define RGBLIGHT_LED_COUNT 6

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_TIMEOUT 30000
#define OLED_BRIGHTNESS 120